### ISSUE TITLE
add old blog post to personal website

### ISSUE THREAD

**Issue by mabdullahadeel** [mabdullahadeel/abdadeel.com#6]
- [x] Reason for Developing in GO
- [x] [Deep Basic Data Types in GO](https://dev.to/abdadeel/all-basic-data-types-in-go-55n8)
- [x] [Shell Scripting Basics: Beginner's Guide](https://dev.to/abdadeel/shell-scripting-basics-beginners-guide-1h2b)
- [x] [100 lines of Elixir](https://dev.to/abdadeel/100-lines-of-elixir-2img)
- [x] [Shell Scripting Basics: Beginner's Guide - Part II](https://dev.to/abdadeel/shell-scripting-basics-beginners-guide-part-ii-4cfo)
- [x] [How to create custom code snippets in VS Code](https://dev.to/abdadeel/how-to-create-custom-code-snippets-in-vs-code-4e7l)
- [x] [How to add real-time notifications with Django and nextjs](https://dev.to/abdadeel/how-to-add-real-time-notifications-with-django-and-nextjs-4p5e)
- [x] [Using Firebase to send real-time notifications in Django apps](https://dev.to/abdadeel/using-firebase-to-send-real-time-notifications-in-django-apps-121h)
- [x] [How to add Discord like QR Code Login](https://dev.to/abdadeel/how-to-add-discord-like-qr-code-login-cn2)
- [x] [MobX - The missing piece in your complex react applications](https://dev.to/abdadeel/mobx-the-missing-piece-in-your-complex-react-applications-5320)
- [x] [Deploying FastAPI app on Vercel Serverless](https://dev.to/abdadeel/deploying-fastapi-app-on-vercel-serverless-18b1)
- [x] [Supercharge Your Web Apps: Harnessing Web Assembly for High Performance](https://dev.to/abdadeel/supercharge-your-web-apps-harnessing-web-assembly-for-high-performance-f4d)
- [x] [We fixed react context 🚀. Using selectors for granular reactivity](https://dev.to/abdadeel/we-fixed-react-context-using-selectors-for-granular-reactivity-3743)
- [x] [Bun 101: Bun for JavaScript Developers](https://dev.to/abdadeel/bun-101-bun-for-javascript-developers-1l68)
- [x] [The Bias Nature of JavaScript Event Loop](https://dev.to/abdadeel/the-bias-nature-of-javascript-event-loop-4i9e)

**Comment by siail** [comment]
re-opened to add remaining blog posts
