### ISSUE TITLE
update the size of site icon

### ISSUE THREAD

**Issue by mabdullahadeel** [mabdullahadeel/abdadeel.com#7]

**Comment by siail** [comment]
The site icon


![Image](https://github.com/mabdullahadeel/abdadeel.com/assets/64294045/54a142ba-5a52-4372-abc1-1bac849b276f)

does not look good on mobile devices. Its a bit oversized. Let's revert back to the text `abdadeel` for now.

**Comment by siail** [comment]
let's update the icon size to fit on all screen sizes
